backend/conf/urls.py
from django.urls import include, path

from survey.views import survey, customers, admins

urlpatterns = [
    path('', include('survey.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('api/', include('survey.api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', survey.SignUpView.as_view(), name='signup'),
    path('accounts/signup/customer/', customers.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/admin/', admins.AdminSignUpView.as_view(), name='admin_signup'),
]

backend/survey/api/urls.py
from rest_framework.routers import DefaultRouter
from .views import (
    UserViewSet, 
    SurveyViewSet, 
    QuestionViewSet,
    AnswerViewSet,
    QuestionAnswerViewSet,
    CustomerAnswerViewSet)

router = DefaultRouter()
router.register(r'users', UserViewSet, base_name='users')
router.register(r'surveys', SurveyViewSet, base_name='surveys')
router.register(r'questions', QuestionViewSet, base_name='questions')
router.register(r'answers', AnswerViewSet, base_name='answers')
router.register(r'question-answers', QuestionAnswerViewSet, base_name='question_answers')
router.register(r'customer-answer', CustomerAnswerViewSet, base_name='customer_answer')

urlpatterns = router.urls

backend/survey/urls.py
from django.urls import include, path

from .views import survey, customers, admins

urlpatterns = [
    path('', survey.home, name='home'),

    path('customers/', include(([
        path('', customers.SurveyListView.as_view(), name='survey_list'),
        path('taken/', customers.TakenSurveyListView.as_view(), name='taken_survey_list'),
        path('survey/<int:pk>/', customers.take_survey, name='take_survey'),
    ], 'survey'), namespace='customers')),

    path('admins/', include(([
        path('', admins.SurveyListView.as_view(), name='survey_change_list'),
        path('survey/add/', admins.SurveyCreateView.as_view(), name='survey_add'),
        path('survey/<int:pk>/', admins.SurveyUpdateView.as_view(), name='survey_change'),
        path('survey/<int:pk>/results/', admins.SurveyResultsView.as_view(), name='survey_results'),
        path('survey/<int:pk>/question/add/', admins.question_add, name='question_add'),
        path('survey/<int:survey_pk>/question/<int:question_pk>/', admins.question_change, name='question_change'),
    ], 'survey'), namespace='admins')),
]

backend/survey/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from survey.models import (Answer, Question, Customer, CustomerAnswer, User)


class AdminSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_admin = True
        if commit:
            user.save()
        return user


class CustomerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.save()
        Customer.objects.create(user=user)
        return user


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', 'answer_type',)


class TakeSurveyForm(forms.ModelForm):
    class Meta:
        model = CustomerAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        if self.question.answer_type == 'text-field' or self.question.answer_type  == 'number-field':
            self.fields['answer'] = forms.CharField(
                widget=forms.TextInput(),
                required=True)
        else:
            self.fields['answer'] = forms.ModelChoiceField(
                queryset=self.question.answers.order_by('text'),
                widget=forms.RadioSelect(),
                required=True,
                empty_label=None)
                
    def clean_answer(self):
        answer = self.cleaned_data['answer']
        if type(answer) == str:
            answer = Answer.objects.create(
                text=answer,
                question=self.question
            )
        return answer

backend/survey/api/views.py
from rest_framework import viewsets
from django.shortcuts import get_object_or_404


from ..models import (
    User, 
    Survey, 
    Question, 
    Customer,
    Answer,
    CustomerAnswer,
    TakenSurvey)
from .serializers import (
    UserSerializer, 
    SurveySerializer, 
    QuestionSerializer, 
    AnswerSerializer,
    QuestionAnswerSerializer,
    CustomerAnswerSerializer)


class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()


class SurveyViewSet(viewsets.ModelViewSet):
    serializer_class = SurveySerializer
    queryset = Survey.objects.all()
    

class QuestionViewSet(viewsets.ModelViewSet):
    serializer_class = QuestionSerializer
    queryset = Question.objects.all()


class AnswerViewSet(viewsets.ModelViewSet):
    serializer_class = AnswerSerializer
    queryset = Answer.objects.all()


class AnswerViewSet(viewsets.ModelViewSet):
    serializer_class = AnswerSerializer
    queryset = Answer.objects.all()


class QuestionAnswerViewSet(viewsets.ModelViewSet):
    serializer_class = QuestionAnswerSerializer
    queryset = TakenSurvey.objects.all()
    http_method_names = ['get',]


class CustomerAnswerViewSet(viewsets.ModelViewSet):
    serializer_class = CustomerAnswerSerializer
    queryset = CustomerAnswer.objects.all()

    def create(self, request):
        customer = request.data.get('customer')
        answer = request.data.get('answer')
        customer = get_object_or_404(Customer, pk=customer)
        survey = get_object_or_404(Answer, pk=answer).question.survey
        customer.surveyes.add(survey)
        TakenSurvey.objects.create(
                                    customer=customer,
                                    survey=survey
                                )
        return super().create(request)

backend/survey/views/admins.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DetailView, ListView, UpdateView)

from ..decorators import admin_required
from ..forms import QuestionForm, AdminSignUpForm
from ..models import Answer, Question, Survey, User


class AdminSignUpView(CreateView):
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('admins:survey_change_list')


@method_decorator([login_required, admin_required], name='dispatch')
class SurveyListView(ListView):
    model = Survey
    ordering = ('name', )
    context_object_name = 'surveyes'
    template_name = 'survey/admins/survey_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.surveyes \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_surveyes', distinct=True))
        return queryset


@method_decorator([login_required, admin_required], name='dispatch')
class SurveyCreateView(CreateView):
    model = Survey
    fields = ('name', )
    template_name = 'survey/admins/survey_add_form.html'

    def form_valid(self, form):
        survey = form.save(commit=False)
        survey.owner = self.request.user
        survey.save()
        messages.success(self.request, 'The survey was created with success! Go ahead and add some questions now.')
        return redirect('admins:survey_change', survey.pk)


@method_decorator([login_required, admin_required], name='dispatch')
class SurveyUpdateView(UpdateView):
    model = Survey
    fields = ('name', )
    context_object_name = 'survey'
    template_name = 'survey/admins/survey_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing surveyes that belongs
        to the logged in user.
        '''
        return self.request.user.surveyes.all()

    def get_success_url(self):
        return reverse('admins:survey_change', kwargs={'pk': self.object.pk})


@method_decorator([login_required, admin_required], name='dispatch')
class SurveyResultsView(DetailView):
    model = Survey
    context_object_name = 'survey'
    template_name = 'survey/admins/survey_results.html'

    def get_context_data(self, **kwargs):
        survey = self.get_object()
        taken_surveyes = survey.taken_surveyes.select_related('customer__user').order_by('-date')
        total_taken_surveyes = taken_surveyes.count()
        extra_context = {
            'taken_surveyes': taken_surveyes,
            'total_taken_surveyes': total_taken_surveyes,
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.surveyes.all()


@login_required
@admin_required
def question_add(request, pk):
    # By filtering the survey by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # survey will be able to add questions to it.
    survey = get_object_or_404(Survey, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.survey = survey
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('admins:question_change', survey.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'survey/admins/question_add_form.html', {'survey': survey, 'form': form})


@login_required
@admin_required
def question_change(request, survey_pk, question_pk):
    # Simlar to the `question_add` view, this view is also managing
    # the permissions at object-level. By querying both `survey` and
    # `question` we are making sure only the owner of the survey can
    # change its details and also only questions that belongs to this
    # specific survey can be changed via this url (in cases where the
    # user might have forged/player with the url params.
    survey = get_object_or_404(Survey, pk=survey_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, survey=survey)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        fields=('text',),
        min_num=2,
        validate_min=True,
        max_num=10,
        validate_max=True
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('admins:survey_change', survey.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'survey/admins/question_change_form.html', {
        'survey': survey,
        'question': question,
        'form': form,
        'formset': formset
    })

backend/survey/views/customers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView

from ..decorators import customer_required
from ..forms import CustomerSignUpForm, TakeSurveyForm
from ..models import Survey, Customer, TakenSurvey, User


class CustomerSignUpView(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'customer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('customers:survey_list')


@method_decorator([login_required, customer_required], name='dispatch')
class SurveyListView(ListView):
    model = Survey
    ordering = ('name', )
    context_object_name = 'surveyes'
    template_name = 'survey/customers/survey_list.html'

    def get_queryset(self):
        customer = self.request.user.customer
        taken_surveyes = customer.surveyes.values_list('pk', flat=True)
        queryset = Survey.objects.exclude(pk__in=taken_surveyes) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, customer_required], name='dispatch')
class TakenSurveyListView(ListView):
    model = TakenSurvey
    context_object_name = 'taken_surveyes'
    template_name = 'survey/customers/taken_survey_list.html'

    def get_queryset(self):
        queryset = self.request.user.customer.taken_surveyes \
            .order_by('survey__name')
        return queryset


@login_required
@customer_required
def take_survey(request, pk):
    survey = get_object_or_404(Survey, pk=pk)
    customer = request.user.customer

    if customer.surveyes.filter(pk=pk).exists():
        return render(request, 'customers/taken_survey.html')
    
    total_questions = survey.questions.count()
    unanswered_questions = customer.get_unanswered_questions(survey)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeSurveyForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                customer_answer = form.save(commit=False)
                customer_answer.customer = customer
                customer_answer.save()
                if customer.get_unanswered_questions(survey).exists():
                    return redirect('customers:take_survey', pk)
                else:
                    TakenSurvey.objects.create(customer=customer, survey=survey)
                    return redirect('customers:survey_list')
    else:
        form = TakeSurveyForm(question=question)

    return render(request, 'survey/customers/take_survey_form.html', {
        'survey': survey,
        'question': question,
        'form': form,
        'progress': progress
    })

backend/survey/views/survey.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_admin:
            return redirect('admins:survey_change_list')
        else:
            return redirect('customers:survey_list')
    return render(request, 'survey/home.html')

backend/survey/templates/survey/admins/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change_list' %}">My Surveyes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change' survey.pk %}">{{ survey.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
  </form>
{% endblock %}

backend/survey/templates/survey/admins/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change_list' %}">My Surveyes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change' survey.pk %}">{{ survey.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    {% if question.answer_type != 'text-field' and question.answer_type != 'number-field' %}
      <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
        <div class="card-header">
          <div class="row">
            <div class="col-8">
              <strong>Answers</strong>
            </div>
          </div>
        </div>
        {% for error in formset.non_form_errors %}
          <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
        {% endfor %}
        <div class="list-group list-group-flush list-group-formset">
          {% for form in formset %}
            <div class="list-group-item">
              <div class="row">
                <div class="col-8">
                  {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                  {{ form.text|as_crispy_field }}
                  {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
      <p>
        <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>10</strong> answers.</small>
      </p>
    {% endif %}
    <button type="submit" class="btn btn-success">Save changes</button>
  </form>
{% endblock %}

backend/survey/templates/survey/admins/survey_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change_list' %}">My Surveyes</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new survey</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new survey</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

backend/survey/templates/survey/admins/survey_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change_list' %}">My Surveyes</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ survey.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ survey.name }}
    <a href="{% url 'admins:survey_results' survey.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'admins:question_change' survey.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'admins:question_add' survey.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'admins:question_add' survey.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
{% endblock %}

backend/survey/templates/survey/admins/survey_change_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Surveyes</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Surveyes</h2>
  <a href="{% url 'admins:survey_add' %}" class="btn btn-primary mb-3" role="button">Add survey</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Survey</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for survey in surveyes %}
          <tr>
            <td class="align-middle"><a href="{% url 'admins:survey_change' survey.pk %}">{{ survey.name }}</a></td>
            <td class="align-middle">{{ survey.questions_count }}</td>
            <td class="align-middle">{{ survey.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'admins:survey_results' survey.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any survey yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

backend/survey/templates/survey/admins/survey_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change_list' %}">My Surveyes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'admins:survey_change' survey.pk %}">{{ survey.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Results</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ survey.name }} Results</h2>

  <div class="card">
    <div class="card-header">
      <strong>Taken Surveyes</strong>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Customer</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_survey in taken_surveyes %}
          <tr>
            <td>{{ taken_survey.customer.user.username }}</td>
            <td>{{ taken_survey.date|naturaltime }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      Total respondents: <strong>{{ total_taken_surveyes }}</strong>
    </div>
  </div>
{% endblock %}